version: '3'
services:
  mysql-server-cluster:
    env_file:
      - mysql-server.env
    image: mysql:8.0
    command: ["mysqld","--server_id=1", "--report-host=node1", "--port=3306","--mysqlx-port=33060", "--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password", "--sql_mode=", "--max-connections=10000"]
    ports:
      - "3306:3306"
      - "33060:33060"
    restart: always
    hostname: node1
    extra_hosts:
      - "node1:192.168.1.2" # is a host ip.
      - "node2:192.168.1.3"
      - "node3:192.168.1.4"
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-password=mysql' ]
      timeout: 20s
      retries: 10
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d/:ro # local path : docker path
      - mysql-data-server-cluster:/var/lib/mysql
  mysql-router:
    env_file:
      - mysql-router.env
    image: mysql/mysql-router:8.0
    ports:
      - "6446:6446"
    extra_hosts:
      - "node1:192.168.1.2" # is a host ip.
      - "node2:192.168.1.3"
      - "node3:192.168.1.4"
    depends_on:
      - mysql-server-cluster
    restart: on-failure
volumes:
  mysql-data-server-cluster: